{% set name = "dask-sql" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: e71ba25e1f24e208aa0c06c4b3bcc1db36e59b50b8260abcd7f18d71a7b944c7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - dask >=2.19.0
    - jpype1 >=1.0.2
    - python >=3.6
    - openjdk >=8
    - fastapi >=0.61.1
    - uvicorn >=0.11.3
    - tzlocal >=2.1

test:
  imports:
    - dask_sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nils-braun/dask-sql/
  summary: SQL Query Layer for dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nils-braun
