{% set name = "dask-sql" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 724af112b76b488fca1027492a52ba17d4dd13c128445237adc529406cf9188a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - dask >=2.19.0
    - jpype1 >=1.0.2
    - python >=3.6
    - pandas <1.2.0
    - openjdk >=8
    - fastapi >=0.61.1
    - uvicorn >=0.11.3
    - tzlocal >=2.1
    - prompt_toolkit >=3.0.8
    - pygments >=2.7.3

test:
  imports:
    - dask_sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nils-braun/dask-sql/
  summary: SQL Query Layer for dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nils-braun
