{% set name = "dask-sql" %}
{% set version = "2022.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 424eea186aadef05e1a9c04e6d13aa399ca56f348c7b31f85f0765e9ffa6c933

build:
  entry_points:
    - dask-sql = dask_sql.cmd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - dask >=2022.3.0,<2022.4.1
    - pandas >=1.0.0
    - jpype1 >=1.0.2
    - openjdk >=8
    - fastapi >=0.61.1
    - uvicorn >=0.11.3
    - tzlocal >=2.1
    - prompt-toolkit
    - pygments
    - nest-asyncio
    - tabulate

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql --help
  requires:
    - pip

about:
  home: http://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
