{% set name = "dask-sql" %}
{% set version = "2022.9.0.rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dask-contrib/dask-sql/archive/{{ version }}.tar.gz
  sha256: 8cf7280cb6529603cb11526932c7485effc6f4efeef22a41a278609bf0a91c9e

build:
  skip: true   # [py2k]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - setuptools-rust >=1.4.1
  host:
    - pip
    - python >=3.8
    - setuptools-rust >=1.4.1
  run:
    - python >=3.8
    - dask >=2022.3.0
    - pandas >=1.4.0
    - fastapi >=0.69.0
    - uvicorn >=0.11.3
    - tzlocal >=2.1
    - prompt-toolkit
    - pygments
    - nest-asyncio
    - tabulate

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: https://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ayushdg
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
